name: image_picker_plus
description: Customization of the gallery display or even camera and video.
version: 0.5.9
homepage: https://github.com/AhmedAbdoElhawary/image_picker_plus.git

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.0.0
  shimmer: ^3.0.0
  camera: 0.10.5+9
  image: ^4.1.7
  video_player: ^2.8.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lykhonis.imagecrop
        pluginClass: ImageCropPlugin
      ios:
        pluginClass: ImageCropPlugin
